---

- name: Install required packages
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - tomcat7
    - unzip
    - apache2

- name: Setup BIRT user
  user: name="{{ birt_viewer.user }}"

# - command: pwda
#   register: result 
#   connection: local
#   sudo: False
  
# - debug:
#     msg: '{{ result }}'
  
- name: Setup authorized keys
  authorized_key: 
    user: "{{ birt_viewer.user }}"
    key: "{{ lookup('file', '%s' % item) }}"
  with_items: birt_viewer.auth_keys

# Install git_access_key. It's better to copy this manually once the playbook has been run once
#- name: Setup git_access_private_key
#  copy: scr="{{ birt_viewer.repo_access_key }}" dest="/home/{{ birt_viewer.user}}/.ssh/{{ birt_viewer.repo_access_key }}" mode=0600

- name: Unzip BIRT viwer package to tmp
  unarchive:
    src: "{{ birt_runtime }}"
    dest: /tmp/
  tags: notthis

- name: Install sql connectors
  copy: 
    src: "{{ item }}"
    dest: "{{ birtviewer_dst }}/WEB-INF/lib/" 
  with_items: 
   - "{{ mysql_connector }}"
   - "{{ psql_connector }}"

- name: Create birtviewer directory
  file: path="{{ birtviewer_dst }}" state=directory

- name: Copy BIRT webapp to birtviewer directory
  shell: cp -rf /tmp/{{ birt_runtime_unzipdir }}/WebViewerExample/* {{ birtviewer_dst }}/
  notify:
    - restart tomcat

- name: "Enable proxy_ajp"
  command: /usr/sbin/a2enmod proxy_ajp
  notify:
    - start apache2
  
- name: "Add default-ssl.conf virtual host configuration"
  sudo: yes
  action: template src=default-ssl.j2 dest=/etc/apache2/sites-available/default-ssl.conf owner=root group=root mode=0640
  notify:
    - restart apache2

- name: Remove tmp files
  shell: rm -rf "/tmp/{{ birt_runtime_unzipdir }}"
